# Generated by Django 5.2.17 on 2026-09-20 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('text_html', models.TextField(blank=True)),
                ('comment_type', models.CharField(blank=True, choices=[('info', 'Info'), ('limit', 'Limit'), ('defect', 'Defect')], max_length=10)),
                ('category', models.SmallIntegerField(blank=True, choices=[(-1, 'Low'), (0, 'Med'), (1, 'High')], null=True)),
                ('multiple_choice_options', models.TextField(blank=True)),
                ('unit_type_options', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('answer_type', models.CharField(blank=True, choices=[('boolean', 'Boolean'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('number', 'Number'), ('range', 'Range'), ('text', 'Text')], max_length=20)),
                ('default_value', models.TextField(blank=True)),
                ('default_value_2', models.TextField(blank=True)),
                ('default_unit_type', models.CharField(blank=True, max_length=100)),
                ('default_location', models.CharField(blank=True, max_length=255)),
                ('default_estimate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_estimate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('simple_format', models.BooleanField(default=False)),
                ('disable_photos', models.BooleanField(default=False)),
                ('uses', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_1_url', models.URLField(blank=True, max_length=1000)),
                ('photo_1_caption', models.CharField(blank=True, max_length=500)),
                ('photo_2_url', models.URLField(blank=True, max_length=1000)),
                ('photo_2_caption', models.CharField(blank=True, max_length=500)),
                ('photo_3_url', models.URLField(blank=True, max_length=1000)),
                ('photo_3_caption', models.CharField(blank=True, max_length=500)),
                ('photo_4_url', models.URLField(blank=True, max_length=1000)),
                ('photo_4_caption', models.CharField(blank=True, max_length=500)),
                ('photo_5_url', models.URLField(blank=True, max_length=1000)),
                ('photo_5_caption', models.CharField(blank=True, max_length=500)),
                ('photo_6_url', models.URLField(blank=True, max_length=1000)),
                ('photo_6_caption', models.CharField(blank=True, max_length=500)),
                ('photo_7_url', models.URLField(blank=True, max_length=1000)),
                ('photo_7_caption', models.CharField(blank=True, max_length=500)),
                ('photo_8_url', models.URLField(blank=True, max_length=1000)),
                ('photo_8_caption', models.CharField(blank=True, max_length=500)),
                ('photo_9_url', models.URLField(blank=True, max_length=1000)),
                ('photo_9_caption', models.CharField(blank=True, max_length=500)),
                ('photo_10_url', models.URLField(blank=True, max_length=1000)),
                ('photo_10_caption', models.CharField(blank=True, max_length=500)),
                ('last_modified_source', models.CharField(blank=True, help_text="Raw 'Last Modified' value from the export.", max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='templates_app.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='templates_app.section'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_template_note', models.TextField(blank=True, help_text='Which template this was exported from, and where it came from.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='templates_app.template')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='templates_app.template'),
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_issues', to='templates_app.template')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
